// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CardPicker",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "CardPicker",
            targets: ["AppModule"],
            bundleIdentifier: "kg.devcats.memorila.cardpicker",
            teamIdentifier: "7W58LXN22D",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("CardArt")
            ]
        )
    ]
)